version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - conf/dev/.env-docker
    environment:
      - MYSQL_ROOT_PASSWORD=testpass
    ports:
      - "3306:3306"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  memcached:
    image: memcached
    restart: always
    ports:
      - 11211:11211

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    command: >
          --requirepass ${REDIS_PASSWORD}

  # app:
  #   build: .
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   command: /bin/bash -c 'chmod +x /app/bin/run_stripe_worker.sh && /app/bin/run_stripe_worker.sh'
  #   env_file:
  #     - conf/dev/.env-docker
  #   depends_on:
  #     - db
