version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - conf/dev/.env-docker
    environment:
      - MYSQL_ROOT_PASSWORD=testpass
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # # Uncomment this if you wish to run your app in docker as would be in production
  # app:
  #   build: .
  #   restart: always
  #   ports:
  #     - "8001:8000"
  # #  command: /bin/bash -c 'chmod +x /app/docker-entrypoint.sh && /app/docker-entrypoint.sh'
  #   env_file:
  #     - conf/dev/.env-docker
  #   depends_on:
  #     - db
