# Generated by Django 4.1.3 on 2022-12-24 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("buyer", models.IntegerField()),
                ("seller", models.IntegerField(blank=True, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("CREDIT_CARD", "Credit card"), ("PAYPAL", "Paypal")],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("EXCHANGE", "Exchange"),
                            ("MINT", "Mint"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZED", "Initialized"),
                            ("REQUIRES_AUTHORIZATION", "Requires authorization"),
                            ("SUCCEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("base_currency", models.CharField(max_length=100)),
                ("quote_currency", models.CharField(max_length=100)),
                ("base_amount", models.FloatField()),
                ("quote_amount", models.FloatField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_changed", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("base_amount__gte", 0.0), ("quote_amount__gte", 0.0)),
                name="positive_amounts",
            ),
        ),
    ]
